[package]
name = "dkms-dev-cli"
version = "0.8.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keri-core = { version = "0.17.2", features = ["oobi", "mailbox"]}
keri-controller = { version = "0.17.2"}
said = { version = "0.4.2", features = ["macros"]}
cesrox = { version = "0.1.7", features = ["cesr-proof"] }
anyhow = { version = "1.0" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.14.0", features = ["rt", "macros", "rt-multi-thread"] }
acdc = { git = "https://github.com/THCLab/acdc-rust"}
messagebox = { git = "https://github.com/THCLab/mesagkesto" }
reqwest =  { version = "0.11.22", features = ["json"]}
clap = { version = "4.4.8", features = ["derive"] }
config-file = {version = "0.2.3", features = ["yaml", "json"]}
ed25519-dalek = {version = "2.1.0", features = ["rand_core"] }
rand = "0.8.5"
thiserror = "1.0.50"
url = "2.4.1"
home = "0.5.5"
indexmap = { version = "2.1.0", features = ["serde"]}
figment = {version="0.10.14", features = ["yaml"]}
serde_yaml = "0.9.30"
base64 = "0.22.1"
tabled = "0.16.0"
futures = "0.3.31"
teliox = { version = "0.17.6"}
tempfile = "3.10.0"
redb = "2.4.0"
serde_cbor = "0.11.2"

[dev-dependencies]

[[bin]]
name = "dkms"
path = "src/main.rs"
